[2025-05-22T14:07:36.852+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-22T14:07:36.892+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_backfill_v02.task1 manual__2025-05-22T14:07:34.842036+00:00 [queued]>
[2025-05-22T14:07:36.907+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_backfill_v02.task1 manual__2025-05-22T14:07:34.842036+00:00 [queued]>
[2025-05-22T14:07:36.916+0000] {taskinstance.py:2884} INFO - Starting attempt 1 of 6
[2025-05-22T14:07:36.971+0000] {taskinstance.py:2907} INFO - Executing <Task(BashOperator): task1> on 2025-05-22 14:07:34.842036+00:00
[2025-05-22T14:07:36.988+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v02', 'task1', 'manual__2025-05-22T14:07:34.842036+00:00', '--job-id', '3940', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmphenled4g']
[2025-05-22T14:07:36.991+0000] {standard_task_runner.py:105} INFO - Job 3940: Subtask task1
[2025-05-22T14:07:36.995+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=583) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-22T14:07:36.997+0000] {standard_task_runner.py:72} INFO - Started process 585 to run task
[2025-05-22T14:07:37.093+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_catchup_backfill_v02.task1 manual__2025-05-22T14:07:34.842036+00:00 [running]> on host 2032228d86df
[2025-05-22T14:07:37.304+0000] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_catchup_backfill_v02' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T14:07:34.842036+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-22T14:07:34.842036+00:00'
[2025-05-22T14:07:37.306+0000] {taskinstance.py:740} INFO - ::endgroup::
[2025-05-22T14:07:37.351+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-05-22T14:07:37.354+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo This is a simple bash command!']
[2025-05-22T14:07:37.388+0000] {subprocess.py:99} INFO - Output:
[2025-05-22T14:07:37.389+0000] {subprocess.py:106} INFO - This is a simple bash command!
[2025-05-22T14:07:37.390+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-05-22T14:07:37.444+0000] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-05-22T14:07:37.445+0000] {taskinstance.py:361} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_backfill_v02, task_id=task1, run_id=manual__2025-05-22T14:07:34.842036+00:00, execution_date=20250522T140734, start_date=20250522T140736, end_date=20250522T140737
[2025-05-22T14:07:37.512+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-22T14:07:37.545+0000] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-22T14:07:37.548+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
