[2025-05-21T16:07:13.373+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-21T16:07:13.438+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_taskflow_api_v02.get_age scheduled__2022-12-07T00:00:00+00:00 [queued]>
[2025-05-21T16:07:13.476+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_taskflow_api_v02.get_age scheduled__2022-12-07T00:00:00+00:00 [queued]>
[2025-05-21T16:07:13.477+0000] {taskinstance.py:2884} INFO - Starting attempt 1 of 6
[2025-05-21T16:07:13.546+0000] {taskinstance.py:2907} INFO - Executing <Task(_PythonDecoratedOperator): get_age> on 2022-12-07 00:00:00+00:00
[2025-05-21T16:07:13.595+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_taskflow_api_v02', 'get_age', 'scheduled__2022-12-07T00:00:00+00:00', '--job-id', '1228', '--raw', '--subdir', 'DAGS_FOLDER/dar_with_taskflow_api.py', '--cfg-path', '/tmp/tmprwkfkr09']
[2025-05-21T16:07:13.599+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3864) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-21T16:07:13.607+0000] {standard_task_runner.py:72} INFO - Started process 3877 to run task
[2025-05-21T16:07:13.606+0000] {standard_task_runner.py:105} INFO - Job 1228: Subtask get_age
[2025-05-21T16:07:13.948+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_taskflow_api_v02.get_age scheduled__2022-12-07T00:00:00+00:00 [running]> on host 2032228d86df
[2025-05-21T16:07:14.209+0000] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_taskflow_api_v02' AIRFLOW_CTX_TASK_ID='get_age' AIRFLOW_CTX_EXECUTION_DATE='2022-12-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-12-07T00:00:00+00:00'
[2025-05-21T16:07:14.216+0000] {taskinstance.py:740} INFO - ::endgroup::
[2025-05-21T16:07:14.221+0000] {python.py:240} INFO - Done. Returned value was: 19
[2025-05-21T16:07:14.335+0000] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-05-21T16:07:14.336+0000] {taskinstance.py:361} INFO - Marking task as SUCCESS. dag_id=dag_with_taskflow_api_v02, task_id=get_age, run_id=scheduled__2022-12-07T00:00:00+00:00, execution_date=20221207T000000, start_date=20250521T160713, end_date=20250521T160714
[2025-05-21T16:07:14.497+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-21T16:07:14.576+0000] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-21T16:07:14.582+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
