[2025-05-21T16:11:44.276+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-21T16:11:44.408+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_taskflow_api_v02.get_age scheduled__2023-09-03T00:00:00+00:00 [queued]>
[2025-05-21T16:11:44.450+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_taskflow_api_v02.get_age scheduled__2023-09-03T00:00:00+00:00 [queued]>
[2025-05-21T16:11:44.453+0000] {taskinstance.py:2884} INFO - Starting attempt 1 of 6
[2025-05-21T16:11:44.558+0000] {taskinstance.py:2907} INFO - Executing <Task(_PythonDecoratedOperator): get_age> on 2023-09-03 00:00:00+00:00
[2025-05-21T16:11:44.601+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_taskflow_api_v02', 'get_age', 'scheduled__2023-09-03T00:00:00+00:00', '--job-id', '2035', '--raw', '--subdir', 'DAGS_FOLDER/dar_with_taskflow_api.py', '--cfg-path', '/tmp/tmp3gr13vmr']
[2025-05-21T16:11:44.602+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=6318) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-21T16:11:44.623+0000] {standard_task_runner.py:72} INFO - Started process 6346 to run task
[2025-05-21T16:11:44.623+0000] {standard_task_runner.py:105} INFO - Job 2035: Subtask get_age
[2025-05-21T16:11:44.771+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_taskflow_api_v02.get_age scheduled__2023-09-03T00:00:00+00:00 [running]> on host 2032228d86df
[2025-05-21T16:11:45.254+0000] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_taskflow_api_v02' AIRFLOW_CTX_TASK_ID='get_age' AIRFLOW_CTX_EXECUTION_DATE='2023-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-03T00:00:00+00:00'
[2025-05-21T16:11:45.256+0000] {taskinstance.py:740} INFO - ::endgroup::
[2025-05-21T16:11:45.261+0000] {python.py:240} INFO - Done. Returned value was: 19
[2025-05-21T16:11:45.334+0000] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-05-21T16:11:45.335+0000] {taskinstance.py:361} INFO - Marking task as SUCCESS. dag_id=dag_with_taskflow_api_v02, task_id=get_age, run_id=scheduled__2023-09-03T00:00:00+00:00, execution_date=20230903T000000, start_date=20250521T161144, end_date=20250521T161145
[2025-05-21T16:11:45.484+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-21T16:11:45.551+0000] {taskinstance.py:3924} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-21T16:11:45.583+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
