[2025-05-21T16:07:22.334+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-21T16:07:22.421+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_taskflow_api_v02.get_age scheduled__2022-12-17T00:00:00+00:00 [queued]>
[2025-05-21T16:07:22.468+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_taskflow_api_v02.get_age scheduled__2022-12-17T00:00:00+00:00 [queued]>
[2025-05-21T16:07:22.469+0000] {taskinstance.py:2884} INFO - Starting attempt 1 of 6
[2025-05-21T16:07:22.660+0000] {taskinstance.py:2907} INFO - Executing <Task(_PythonDecoratedOperator): get_age> on 2022-12-17 00:00:00+00:00
[2025-05-21T16:07:22.696+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_taskflow_api_v02', 'get_age', 'scheduled__2022-12-17T00:00:00+00:00', '--job-id', '1254', '--raw', '--subdir', 'DAGS_FOLDER/dar_with_taskflow_api.py', '--cfg-path', '/tmp/tmp8ua8j0uu']
[2025-05-21T16:07:22.698+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3941) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-21T16:07:22.736+0000] {standard_task_runner.py:105} INFO - Job 1254: Subtask get_age
[2025-05-21T16:07:22.736+0000] {standard_task_runner.py:72} INFO - Started process 3956 to run task
[2025-05-21T16:07:23.018+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_taskflow_api_v02.get_age scheduled__2022-12-17T00:00:00+00:00 [running]> on host 2032228d86df
[2025-05-21T16:07:23.440+0000] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_taskflow_api_v02' AIRFLOW_CTX_TASK_ID='get_age' AIRFLOW_CTX_EXECUTION_DATE='2022-12-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-12-17T00:00:00+00:00'
[2025-05-21T16:07:23.445+0000] {taskinstance.py:740} INFO - ::endgroup::
[2025-05-21T16:07:23.449+0000] {python.py:240} INFO - Done. Returned value was: 19
[2025-05-21T16:07:23.575+0000] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-05-21T16:07:23.576+0000] {taskinstance.py:361} INFO - Marking task as SUCCESS. dag_id=dag_with_taskflow_api_v02, task_id=get_age, run_id=scheduled__2022-12-17T00:00:00+00:00, execution_date=20221217T000000, start_date=20250521T160722, end_date=20250521T160723
[2025-05-21T16:07:23.926+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-21T16:07:24.077+0000] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-21T16:07:24.095+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
